global:
  scrape_interval: 15s
  evaluation_interval: 15s # Оценивать правила каждые 15сек

rule_files:
#  - "first_rules.yml"
#  - "second_rules.yml"

scrape_configs: # как собирать логи
  - job_name: 'prometheus'

    static_configs:
      - targets: [127.0.0.1:9090] # с локального хоста

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['host.docker.internal:8081'] # откуда выгребать